all: Moto Twingo

Roue:
	javac Roue.java

Moteur:
	javac Moteur.java
	
Personne:
	javac Personne.java

Voiture: Roue Moteur
	javac Voiture.java

Moto: Roue Moteur
	javac Moto.java

Twingo: Voiture Personne
	javac Twingo.java

