all : Etat EtatLibre EtatPossede Propriete Joueur
	javac Monopoly.java

Joueur:
	javac Joueur.java
	
Propriete:
	javac Propriete.java
	
Etat:
	javac Etat.java

EtatLibre:
	javac EtatLibre.java
	
EtatPossede:
	javac EtatPossede.java
