# Makefile permettant de lancer la résolution
# des différents problèmes du TP 1
# Auteur : Thomas Minier, groupe 601A

# Résolution de l'exercice 2-1
ex21:
	glpsol --model ex2-1.mod -d ex2-1.dat

# Résolution de l'exercice 2-2
ex22:
	glpsol --model ex2-2.mod -d ex2-2.dat